name: Test

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * SAT'
  pull_request:
    branches:
      - master
  release:
    types: # This configuration does not affect the page_build event above
      - created
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
        - ubuntu-latest
        - windows-latest
        channel:
        - stable
        - beta
        - nightly

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
    - name: Install latest ${{ matrix.channel }}
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.channel }}
          default: true
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      env:
        RSTEST_TEST_CHANNEL: ${{ matrix.channel }}
      run: cargo test --all --verbose

  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack
    - run: cargo hack check --rust-version --workspace --ignore-private
    - run: |
        cargo hack test --rust-version --workspace \
          --exclude rstest_reuse --ignore-private \
          -- --skip rstest::ignore_attributes_args_if_any
